# Generated by Django 6.0.5 on 2026-06-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_desc_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('packaging', 'Qadoqlash'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Qaytib'), ('pending', 'Keyin oladi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.flow')),
            ],
        ),
    ]
