# Generated by Django 6.0.5 on 2026-06-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apps.flow'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('packaging', 'Qadoqlash'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('pending', 'Keyin oladi'), ('returned', 'Qaytib keldi'), ('cancelled', 'Bekor qilindi'), ('hold', 'Hold'), ('archive', 'Arxiv')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='apps.flow')),
            ],
        ),
    ]
