# Generated by Django 6.0.5 on 2026-06-11 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_order_full_name_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
